- src/Slackbot.Net.Extensions.FplBot/Abstractions/ITransfersByGameWeek.cs
- src/Slackbot.Net.Extensions.FplBot/Handlers/FplTransfersCommandHandler.cs
- src/Slackbot.Net.Extensions.FplBot/Helpers/TransfersByGameWeek.cs
- src/Slackbot.Net.Extensions.FplBot/RecurringActions/NextGameweekRecurringAction.cs
- src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Trakk ut transfersforgameweek i en egen klasse for å gjenbruke i bakgrunnsjobb-tingen som kjører når en ny gameweek er i gang.
Håpet er å få captains + transfers som en del av "Ny gameweek"-alert.
> Adds listing of transfers on new-gw-notification

- src/FplBot.WebApi.Tests/RedisIntegrationTests.cs
- src/FplBot.WebApi/Data/RedisOptions.cs
- src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs
- src/FplBot.WebApi/Startup.cs
Moves to match name of injected secrets in Heroku, since Heroku updates these values when patching Redis instances and disregards our current custom ones.
> Migrate to using Herokus REDIS_URL for configuration

- src/FplBot.WebApi.Tests/RedisIntegrationTests.cs
The test suite will flush the entire db (delete all data), so using a sep redis instance for it to avoid deleting data for developers.
NB, redis integration tests are still skipped in the test suite. Waiting to enable it until everyone is working off latest in master.
> Use a separate instance for integration tests

- src/Slackbot.Net.Extensions.FplBot/RecurringActions/NearDeadlineRecurringAction.cs
Uses first gw as current if none are current.
> Bugfix: Near deadline first gw

- src/FplBot.Tests/StateTests.cs
- src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs
- src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsHandler.cs
- src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsMonitor.cs
- src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs
Legger til rette for å håndtere andre ulike typer events ved bruk av C# event handlers, slik at de blir mest mulig uavhengige (minst mulige koblinger, eller try-catches). Tenkte f.eks. å legge til "player injurered" eventet i en senere PR.
> Refactor fixture-events handling into C# event handlers

- src/Fpl.Search/Fpl.Search.csproj
- src/Fpl.Search/Indexing/IIndexProvider.cs
- src/Fpl.Search/Indexing/IndexingClient.cs
- src/Fpl.Search/Indexing/IndexingService.cs
- src/Fpl.Search/Indexing/QueryAnalyticsIndexingService.cs
- src/Fpl.Search/Models/EntryItem.cs
- src/Fpl.Search/Models/IIndexableItem.cs
- src/Fpl.Search/Models/LeagueItem.cs
- src/Fpl.Search/Models/QueryAnalyticsItem.cs
- src/Fpl.Search/Models/SearchResult.cs
- src/Fpl.Search/SearchServiceCollectionExtensions.cs
- src/Fpl.Search/Searching/SearchService.cs
- src/Fpl.SearchConsole/Fpl.SearchConsole.csproj
- src/Fpl.SearchConsole/Program.cs
- src/Fpl.SearchConsole/ServiceCollectionExtensions.cs
- src/FplBot.Messaging.Contracts/Commands/v1/IndexQuery.cs
Replaces synchronous indexing job of analytics with publishing a command onto Azure Service Bus
Other:
- Removes empty marker interface `IIndexableItem`
- Replace `QueryAnalyticsItem` with a message _command_ contract `IndexQuery` (index this query plz)
- Removes try-catch in indexing analytics method, since the message will end up on the error queue instead (indexing analytics will no longer fail the search function since the process now is async)
> Move out indexing search executed search terms to async handler

- src/FplBot.Core/Handlers/FplEvents/GameweekEndedUpdateStatsHandler.cs
These stats (transfers/captains/self-ownership) are ready on gw-start, no need to wait for gw end
> Update stats on gw-start instead of gw-end

- src/FplBot.Core/Data/VerifiedEntriesRepository.cs
- src/FplBot.Core/Handlers/FplEvents/FixtureFulltimeUpdateStatsHandler.cs
- src/FplBot.Core/Handlers/FplEvents/GameweekEndedUpdateStatsHandler.cs
- src/FplBot.Core/Handlers/InternalCommands/UpdateEntryStatsCommandHandler.cs
- src/FplBot.Core/Handlers/InternalCommands/UpdateOngoingStatsCommandHandler.cs
- src/FplBot.WebApi/Pages/Admin/Verified.cshtml
- src/FplBot.WebApi/Pages/Admin/Verified.cshtml.cs
- Live stats updates are triggered by the FixtureFulltime event (good enough, often enough @skjelbek ?)
- Updates the following stats for all verified accounts:  CurrentGwTotalPoints, OverallRank, PointsThisGw
> Update live scores for verified accounts during ongoing gw

- src/FplBot.Core/Handlers/InternalCommands/UpdateVerifiedEntriesCurrentGwPointsCommandHandler.cs
Sjekker ut om entry-API-et har mer oppdaterte live-data enn history-endepunktet hver natt 🤷‍♂️
> Changes from history API to entry API for score update

- src/FplBot.Core/Helpers/SlackHandleHelper.cs
- src/FplBot.Tests/Formatting/FixtureEventsFormattingTests.cs
- Use <@user_id> instead of @username
- Source: https://api.slack.com/changelog/2017-09-the-one-about-usernames
Fixes #239
> Bugfix for slack user mentions in taunts

- src/Fpl.Workers/Models/Mappers/MatchDetailsMapper.cs
- src/Fpl.Workers/States/LineupState.cs
- This feature relies on scraping the HTML on premierleague.com, so it's quite brittle.
- Added some more try-catches for non-happy paths.
> Hotfix: lineups parsing

- src/Fpl.Workers/Events/PublicEvents.cs
- src/Fpl.Workers/Fpl.Workers.csproj
- src/Fpl.Workers/Models/Mappers/PlayerChangesEventsExtractor.cs
- src/Fpl.Workers/Models/PlayerUpdate.cs
- src/Fpl.Workers/States/State.cs
- src/FplBot.Core/Handlers/FplEvents/NewPlayerHandler.cs
- src/FplBot.Core/Handlers/FplEvents/PriceChangeHandler.cs
- src/FplBot.Core/Helpers/Formatting/Formatter.cs
- src/FplBot.Messaging.Contracts/Commands/v1/PublishNewPlayersToSlackWorkspace.cs
- src/FplBot.Messaging.Contracts/Commands/v1/PublishPriceChangesToSlackWorkspace.cs
- src/FplBot.Messaging.Contracts/Events/v1/NewPlayersRegistered.cs
- src/FplBot.Messaging.Contracts/Events/v1/PlayersPriceChanged.cs
- src/FplBot.Tests/FplBot.Tests.csproj
- src/FplBot.Tests/Helpers/TestBuilder.cs
- src/FplBot.Tests/PriceMonitorTests.cs
- src/FplBot.Tests/StateTests.cs
**Goal**: _Using some events as a test of using nservicebus for handling scale and fault tolerance._
- Moves 2 "less important" notifications to use nservicebus instead of mediatr to try it out
- This PR splits the current sequential slack publishing (foreach worskspace -> publish) into separate commands, allowing for both scale out and fault tolerance.
Ex: 
1. The worker process submits a single "newplayersevent" onto the queue.
2. A listener to the event consumes it, and publishes 1 new command pr slack: "publishnewplayerstoworkspace".
3. A listener to the command creates the formatted slack message and executes the publishing to the single workspace.
This approach might look more verbose/chatty, but is more decoupled, fault tolerant and rigged for scale. 
**Fault taulerance**
By …
> Recoverability: Test queue instead of in-mem

- src/Fpl.Workers/Events/PublicEvents.cs
- src/Fpl.Workers/Models/Mappers/PlayerChangesEventsExtractor.cs
- src/Fpl.Workers/States/State.cs
- src/FplBot.Core/Extensions/PlayerExtensions.cs
- src/FplBot.Core/Handlers/FplEvents/InjuryUpdateHandler.cs
- src/FplBot.Core/Helpers/Formatting/Formatter.cs
- src/FplBot.Messaging.Contracts/Events/v1/InjuryUpdateOccured.cs
- src/FplBot.Tests/Formatting/InjuryFormattingTests.cs
- src/FplBot.Tests/NearDeadlineTests.cs
- src/FplBot.Tests/StateTests.cs
- src/FplBot.WebApi/Program.cs
🚃 Migrates injury update notifications from in-mem MediatR messaging onto Azure ServiceBus
🦠 Removes XUnit build warnings
> Move injury notifications to ASB transport

- src/Fpl.Client/Models/StatType.cs
- src/Fpl.Workers/Events/InternalEvents.cs
- src/Fpl.Workers/Events/PublicEvents.cs
- src/Fpl.Workers/Extensions/EnumerableExtensions.cs
- src/Fpl.Workers/Models/FixtureEvents.cs
- src/Fpl.Workers/RecurringActions/GameweekLifecycleMonitor.cs
- src/FplBot.Core/Extensions/StatTypeMethods.cs
- src/FplBot.Core/Handlers/FplEvents/GameweekJustBeganUpdateStatsHandler.cs
- src/FplBot.Core/Handlers/FplEvents/GameweekStartedHandler.cs
- src/FplBot.Core/Handlers/InternalCommands/UpdateEntryStatsCommandHandler.cs
- src/FplBot.Core/Helpers/EnumerableExtensions.cs
- src/FplBot.Core/ServiceCollectionExtensions.cs
- src/FplBot.Messaging.Contracts/Commands/v1/ProcessGameweekStartedForSlackWorkspace.cs
- src/FplBot.Messaging.Contracts/Events/v1/GameweekJustBegan.cs
- src/FplBot.Tests/GameweekLifecycleRecurringActionTests.cs
- src/FplBot.Tests/Helpers/Factory.cs
- src/FplBot.WebApi/FplBot.WebApi.csproj
- src/FplBot.WebApi/Startup.cs
- Puts captains&transfers messaging triggered by `GameweekJustsBegan` event onto the  🚌  
- Small move towards making fpl worker and slackbot less coupled
> Moves GameweekJustStarted messaging from in-mem MediatR to ASB

- src/Fpl.Workers/Extensions/EnumerableExtensions.cs
- src/Fpl.Workers/Models/FinishedFixture.cs
- src/Fpl.Workers/Models/Mappers/LiveEventsExtractor.cs
- src/Fpl.Workers/States/State.cs
- src/FplBot.Core/FplBot.Core.csproj
- src/FplBot.Core/Handlers/FplEvents/FixtureFulltimeHandler.cs
- src/FplBot.Core/Handlers/SlackEvents/UnknownAppMentionCommandHandler.cs
- src/FplBot.Core/Helpers/ChipsPlayed.cs
- src/FplBot.Core/Helpers/EnumerableExtensions.cs
- src/FplBot.Core/Helpers/Formatting/Formatter.cs
- src/FplBot.Tests/Formatting/FulltimeFormattingTests.cs
- src/FplBot.Tests/FplBot.Tests.csproj
Removes coupling to Fpl.Worker in Slackbot (`FplBot.Core`):
https://github.com/fplbot/fplbot/blob/1343da0ddb0300eaf22bac3909ebfa7ac2569274/src/FplBot.Core/FplBot.Core.csproj#L20
The FPL event emitter a.k.a. `Fpl.Worker` and the Slackbot (a.k.a. `FplBot.Core`) are now entirely independent of each other allowing for scaling handlers different to emitters. The workers and the handlers are still kept hosted in the same host until we see a need to scale up handlers.
> Removes coupling between event emitter and event handlers

- .github/release.yml
- .github/workflows/DeployToProd.yml
- Adds contributors recognition and some nicer mrkdown formatting
- [Blog post](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/#introducing-auto-generated-release-notes), [GitHub CLI teams own usage](https://github.com/cli/cli/pull/4512/files), [Docs 1](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes), [Docs 2](https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release)
> Use GitHub API for release notes

- src/FplBot.Discord/Handlers/FplEvents/FixtureEventsHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/FixtureFulltimeHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/GameweekFinishedHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/GameweekStartedHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/InjuryUpdateHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/LineupReadyHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/NearDeadlineHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/NewPlayersHandler.cs
- src/FplBot.Discord/Handlers/FplEvents/PriceChangeHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/FixtureEventsHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/FixtureFulltimeHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/GameweekFinishedHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/GameweekStartedHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/InjuryUpdateHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/LineupReadyHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/NearDeadlineHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/NewPlayerHandler.cs
- src/FplBot.Slack/Handlers/FplEvents/PriceChangeHandler.cs
**Bug:**
* On each FPL event, we loop all fplbot installs and send a command for each individual workspace/server. 
* All the send operations are enlisted in a transaction by NServicebus (default behaviour).
* The Azure Service Bus transport we use has a limit of 100 messages pr transaction.
* At some point we hit a total no of slack workspaces + discord servers to be >= 100. 
**Fix:**
Every handler that sends an unknown count of messages needs to either
1) batch send: keep transactions, but send in a way that number of messages are always below 100
2) disable transactions. 
Since we don't do _other_ work that could lead to failure inside the dispatcher loops, I think it's ok to simply disable transactions in those.
Our (pseudo) code:
```csharp
foreach(sub in subs){
await …
```
> Removes transactions from dispatching message handlers

- src/FplBot.Discord/Handlers/PublishToGuildHandler.cs
Discord scenarios:
- Bot uninstalled (we don't get notice from Discord on uninstalls like we do for Slack)
- Setup a subscription in a channel without giving the bot permissions (fplbot role needs access if private discord channel).
Not sure if we can diff between an uninstall or private channel yet. Might want to just delete the Discord server and/or the sub if we cannot post to any channel in a server.
> Discord: don't put unauthorized message to error queue

- src/FplBot.Discord/Handlers/FplEvents/GameweekStartedHandler.cs
- src/FplBot.Formatting/Helpers/CaptainsByGameWeek.cs
- src/FplBot.Formatting/Helpers/ICaptainsByGameWeek.cs
- src/FplBot.Slack/Handlers/FplEvents/GameweekStartedHandler.cs
- src/FplBot.Slack/Handlers/SlackEvents/FplCaptainCommandHandler.cs
Reduces pushing large content to clients. Some servers/worksapces with subs for larger leagues does not have the same connection to each individual FPL manager as in the smaller leagues (say, a smaller group of friends/colleagues). For these larger leagues, we just push stats instead with a link to full details on our web site. 
**Smaller league**
**Larger league**
> Large leagues: minimize large gw-started content to stats/links

- src/FplBot.Formatting/FixtureStats/GameweekEventsFormatter.cs
The API game time is based on does not update during the match as expected. It keeps it to minute 0 until the game is finished. Then it switches to 90 after a while. Basically unusable. Need to find another source for game time.
> Temporary fix: Disable gametime in fixtureevents

- src/Fpl.EventPublishers.Console/HostBuilderExtensions.cs
- src/Fpl.EventPublishers/RecurringActions/MatchDayStatusRecurringAction.cs
- src/Fpl.EventPublishers/States/GameweekLifecycleMonitor.cs
- src/Fpl.EventPublishers/States/LineupState.cs
- src/Fpl.EventPublishers/States/MatchDayStatusMonitor.cs
- src/Fpl.EventPublishers/States/NearDeadLineMonitor.cs
- src/FplBot.EventHandlers.Console/FplBot.EventHandlers.Console.csproj
- src/FplBot.EventHandlers.Console/HostBuilderExtensions.cs
- src/FplBot.Formatting/Helpers/LeagueEntriesByGameweek.cs
- src/FplBot.Formatting/TransfersByGameWeek.cs
- src/FplBot.WebApi/Controllers/DebugController.cs
- src/FplBot.WebApi/FplBot.WebApi.csproj
- src/FplBot.WebApi/Infrastructure/HostBuilderExtensions.cs
- Logs WRN instead of ERR when 529 Service Unavailable from the FPL API (a.k.a. "The game is updating").
- Uses weird Serilog trick to keep scope (correlationId) in stacktraces: https://andrewlock.net/how-to-include-scopes-when-logging-exceptions-in-asp-net-core/#using-exception-filters-to-capture-scopes
> Game is updating

- src/Fpl.EventPublishers/Extensions/ILoggerExtensions.cs
- src/Fpl.EventPublishers/Mediators/LineupsMediator.cs
- src/Fpl.EventPublishers/Mediators/StateEventsHandler.cs
- src/Fpl.EventPublishers/RecurringActions/GameweekLifecycleRecurringAction.cs
- src/Fpl.EventPublishers/RecurringActions/MatchDayStatusRecurringAction.cs
- src/Fpl.EventPublishers/RecurringActions/NearDeadlineRecurringAction.cs
- src/Fpl.EventPublishers/States/GameweekLifecycleMonitor.cs
- src/Fpl.EventPublishers/States/LineupState.cs
- src/Fpl.EventPublishers/States/MatchDayStatusMonitor.cs
- src/Fpl.EventPublishers/States/NearDeadLineMonitor.cs
- src/Fpl.EventPublishers/States/State.cs
- src/FplBot.Data/Discord/EventSubscription.cs
- src/FplBot.Data/Slack/EventSubscription.cs
- src/FplBot.EventHandlers.Discord/FixtureRemovedFromGameweekHandler.cs
- src/FplBot.EventHandlers.Discord/PublishToGuildHandler.cs
- src/FplBot.EventHandlers.Slack/FixtureRemovedFromGameweekHandler.cs
- src/FplBot.Messaging.Contracts/Events/v1/FixtureRemovedFromGameweek.cs
- src/FplBot.Tests/MatchStatusTests.cs
- src/FplBot.WebApi/Controllers/DebugController.cs
- src/ext/Discord.Net.HttpClients/DiscordClient.cs
Adds new notifications on `FixtureRemovedFromGameweek` events ( fixture is removed from a gameweek).
TODO:
> Adds notifications when a fixture is off

- .github/workflows/DeployToProd.yml
- It's deprecated, https://github.com/actions/create-release/issues/119
- The GitHub CLI now has feature parity, https://cli.github.com/manual/gh_release_create
> Removes deprecated GitHub Action actions/create-release

- src/Fpl.EventPublishers.Console/Fpl.EventPublishers.Console.csproj
- src/Fpl.Search.CommandLine/Program.cs
- src/Fpl.Search.Indexer.Console/HerokuRedisConfigParser.cs
- src/Fpl.Search/Data/SearchRedisOptions.cs
- src/FplBot.Data/FplBot.Data.csproj
- src/FplBot.Data/Slack/RedisOptions.cs
- src/FplBot.VerifiedEntries/Data/VerifiedRedisOptions.cs
- src/FplBot.VerifiedEntries/FplBot.VerifiedEntries.csproj
- src/FplBot.VerifiedEntries/ServiceCollectionExtensions.cs
- src/FplBot.WebApi.Discord/FplBot.WebApi.Discord.csproj
- src/FplBot.WebApi.Slack/FplBot.WebApi.Slack.csproj
- src/FplBot.WebApi.Tests/FplBot.WebApi.Tests.csproj
- src/FplBot.WebApi.Tests/RedisIntegrationTests.cs
- src/FplBot.WebApi/FplBot.WebApi.csproj
- src/FplBot.WebApi/Infrastructure/WebApplicationBuilderExtensions.cs
Forced update to Redis 7 from Heroku.
Fixes:
- Upgrades `StackExchange.Redis` to latest
- Ignores enforced SSL validation on Redis connections (it looks like the [recommended approach](https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-node-js))
> Bugfix: Ignores required SSL reqs w/Redis 7

- src/Fpl.EventPublishers.Console/HerokuRedisConfigParser.cs
- src/Fpl.Search.Indexer.Console/HerokuRedisConfigParser.cs
- src/FplBot.EventHandlers.Console/HerokuRedisConfigParser.cs
Last bugfix only took care of the API. This PR fixes the same issue for:
- EventPublisher
- Indexer
- EventHandler
> Adds redis hack to non-API components

- src/Fpl.EventPublishers/Mediators/LineupsMediator.cs
Fixes a small season-finished-bug, where bot would try to check for lineups in non-existing "next" gw 39 (38+1):
```
[INF] Fpl.EventPublishers.Mediators.LineupsHandler: Refreshing state for finished gw 38. Using next gw 39
[ERR] Fpl.EventPublishers.RecurringActions.GameweekLifecycleRecurringAction Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at Fpl.EventPublishers.States.LineupState.Refresh(Int32 gw) in /app/Fpl.EventPublishers/States/LineupState.cs:line 78
at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
at Fpl.EventPublishers.States.GameweekLifecycleMonitor.EveryOtherMinuteTick(CancellationToken token) in …
```
> Bugfix: dont check for lineups after gw38

- src/FplBot.Formatting/Formatter.cs
Typically if league was started mid-season, there would be no entries. 
`Enumerable.Average` throws exceptions when enumerable has no elements:
```
System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)
at FplBot.Formatting.Formatter.FormatGameweekFinished(Gameweek gw, ClassicLeague league) in /app/FplBot.Formatting/Formatter.cs:line 420
at FplBot.EventHandlers.Discord.GameweekFinishedHandler.Handle(PublishGameweekFinishedToGuild message, IMessageHandlerContext context) in /app/FplBot.EventHandlers.Discord/GameweekFinishedHandler.cs:line 57
```
https://github.com/fplbot/fplbot/blob/0a01ec1a01ce53dc31b6e399783e06b62bb95419/src/FplBot.Formatting/For …
> Bugfix: standings when no entries for gw

- src/Fpl.Client/Models/ClassicLeagueStandings.cs
- src/FplBot.EventHandlers.Discord/GameweekFinishedHandler.cs
- src/FplBot.EventHandlers.Slack/GameweekFinishedHandler.cs
- src/FplBot.EventHandlers.Slack/Helpers/SlackWorkSpacePublisher.cs
- src/FplBot.Formatting/Formatter.cs
No idea why, and did not bother to investigate: 7 Slack workspaces did not have a "worst" entry in GW1. Not seen the same issue in Discord, so a bit odd. Added som null handling around Slack + formatting of standings on gameweek finished events.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at FplBot.Formatting.ClassicLeagueEntryExtensions.GetEntryLink(ClassicLeagueEntry entry, Nullable`1 gameweek) in /app/FplBot.Formatting/ClassicLeagueEntryExtensions.cs:line 14
at FplBot.Formatting.Formatter.GetWorstGameweekEntry(ClassicLeague league, Gameweek gameweek, Boolean includeExternalLinks) in /app/FplBot.Formatting/Formatter.cs:line 75
at FplBot.EventHandlers.Slack.GameweekFinishedHandler.Handle(PublishStandingsToSlackWorkspace message, …
```
> 🪲 Bugfix: worst entry is null sometimes

- src/Fpl.Client/Models/Fixture.cs
- src/Fpl.EventPublishers/Models/Mappers/LiveEventsExtractor.cs
- src/FplBot.Tests/GetUpdatedFixtureEventsTests.cs
- src/FplBot.Tests/Helpers/TestBuilder.cs
Relates to [#317-Goal Score Notifications Wrong](https://github.com/fplbot/fplbot/issues/317)
`team_h_score` & `team_a_score` are often out of sync with the `goal_scored` stats. This change moves to calculate the home and away goal tally instead.
Solves #317
> Moves from stale properties to calculate fixture score from stats array

- src/Fpl.Client/Models/Pick.cs
- src/FplBot.EventHandlers.Discord/GameweekStartedHandler.cs
- src/FplBot.Formatting/ClassicLeagueEntryExtensions.cs
- src/FplBot.Formatting/Formatter.cs
- src/FplBot.Formatting/TransfersByGameWeek.cs
- src/FplBot.WebApi/Endpoints/Test/DebugRoute.cs
- src/FplBot.WebApi/Endpoints/Test/Gameweekstart/TestGwStart.cs
- test.http
Discord has a max-limit of 2000 chars pr chat message. In the event of large count of transfers (wildcards, free hits), the messages we send hit this limit (current chunking is not perfect). This PR chunks messages into even smaller pieces, and changes how we display the transfers when managers use wildcards/free hits:
- ♻️ _Show the number of transfers done instead of every single transfer made._
- 🆕 _Show the final eleven picks similar to the lineups._
> Improve handling of large notifications on Discord
