fplbot/fplbot

src/FplBot.ConsoleApps/Clients/FplClient.cs, src/FplBot.ConsoleApps/Clients/FplClientOptionsConfigurator.cs, src/FplBot.ConsoleApps/Clients/IFplClient.cs, src/FplBot.ConsoleApps/Program.cs, src/FplBot.Tests/FplPlayerCommandHandlerTests.cs, src/FplBot.Tests/Helpers/Factory.cs
- Bare litt cleanup, så man setter baseUrl en gang i setup globalt på httpclient, og bare angir relative URLer i FplClient
=> Configures baseUrl on FplClient

.github/workflows/CI.yml, .github/workflows/Release.yml, README.md, build/FplBot.Build.csproj, build/TheNukeBuild.cs, src/.dockerignore, src/rundockerhubcontainer.sh
Just because I wanted to test Docker build & deploy via GitHub actions :)
=> Publishes fplbot as a docker image to DockerHub

src/FplBot.ConsoleApps/FplbotOptions.cs, src/FplBot.ConsoleApps/IFplBotServiceCollectionExtensions.cs, src/FplBot.ConsoleApps/RecurringActions/NextGameweekRecurringAction.cs
Polls every minute and checks if there is any change to what gameweek is marked as "Current"
=> Notify on new gameweek

src/FplBot.Tests/Helpers/Factory.cs, src/FplBot.Tests/NearDeadlineTests.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/DateTimeUtils.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/NearDeadlineRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Sjekker én gang i minuttet om det er 60 minutter til deadline, og gir en lyd fra seg dersom det stemmer. 🤞
=> Adds near deadline notification

src/FplBot.ConsoleApps/FplBot.ConsoleApps.csproj, src/FplBot.Tests/Helpers/Factory.cs, src/FplBot.WebApi/Controllers/OAuthController.cs, src/FplBot.WebApi/FplBot.WebApi.csproj, src/Slackbot.Net.Extensions.FplBot/Helpers/MessageHelper.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/NextGameweekRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/Slackbot.Net.Extensions.FplBot.csproj
=> Adds transfers back to gameweek commencing alert

src/FplBot.WebApi/Controllers/OAuthController.cs, src/FplBot.WebApi/Data/ISlackTeamRepository.cs, src/FplBot.WebApi/Data/RedisOptions.cs, src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs, src/FplBot.WebApi/Data/SlackTeam.cs, src/FplBot.WebApi/DistributedSlackAppOptions.cs, src/FplBot.WebApi/FplBot.WebApi.csproj, src/FplBot.WebApi/Startup.cs, src/FplBot.WebApi/appsettings.json
=> Hooks up Fplbot as a distributed app

src/FplBot.Tests/FplTransfersCommandHandlerTests.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/ITransfersByGameWeek.cs, src/Slackbot.Net.Extensions.FplBot/Extensions/EnumerableExtensions.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplTransfersCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/TransfersByGameWeek.cs
(don't worry, the team names are still links, I just faked a screenshot)
=> Improve the transfers handler

src/FplBot.WebApi/Controllers/OAuthController.cs, src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs, src/FplBot.WebApi/Data/SlackTeam.cs, src/FplBot.WebApi/Pages/Install.cshtml, src/FplBot.WebApi/Pages/Install.cshtml.cs, src/FplBot.WebApi/Pages/Success.cshtml, src/FplBot.WebApi/Pages/Success.cshtml.cs, src/FplBot.WebApi/Startup.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IFetchFplbotSetup.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/GameweekRecurringActionBase.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/NearDeadlineRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
* Adds UI with install link
* Storing channel/leagueId to Redis along with token
* Adds success page (after install)
=> Creates UI for taking channel and leagueId in on install

src/FplBot.Tests/GetUpdatedFixtureEventsTests.cs, src/FplBot.Tests/TestBuilder.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/GameweekMonitorRecurringAction.cs
Extracts nullref throwing code to a static method and puts it under test
=> Add gw monitoring tests

src/FplBot.Tests/GameweekLifecycleRecurringActionTests.cs, src/FplBot.Tests/GameweekMonitorOrchestratorTests.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IGameweekMonitorOrchestrator.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IHandleGameweekEnded.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/GameweekMonitorOrchestrator.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/GameweekEndedNotifier.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/GameweekLifecycleRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Attempt at pushing standings at end of gameweek. No idea at what time the event will actually trigger.
=> Post standings on gameweek finished

src/FplBot.WebApi/Controllers/OAuthController.cs
Checking FPL API if league exists as a classic league before going ahead with installation.
=> Simple classic leagueId validation on install

src/Directory.Build.targets, src/FplBot.Tests/Helpers/CustomAssert.cs, src/FplBot.Tests/StateTests.cs, src/FplBot.Tests/TestBuilder.cs, src/FplBot.WebApi/appsettings.json, src/Slackbot.Net.Extensions.FplBot/Abstractions/GameweekLeagueContext.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/ISlackWorkSpacePublisher.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/Constants.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/GameweekEventsFormatter.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/SlackHandleHelper.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/SlackWorkSpacePublisher.cs
* Added the same tests as PR https://github.com/fplbot/fplbot/pull/65
* Move `slack.userslist` fetching to State.Reset and put into GameweekContext so it's only fetched once at startup
=> Adds @skjelbek taunts

src/FplBot.Tests/PriceMonitorTests.cs, src/FplBot.Tests/TestBuilder.cs, src/Slackbot.Net.Extensions.FplBot/Constants.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplPricesHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/PriceMonitoring/PriceChanged.cs, src/Slackbot.Net.Extensions.FplBot/PriceMonitoring/PriceChangedMonitor.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/PriceChangedRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
* Recurring action to notify when it happens (don't know when!)
* Command handler to query manually using `@fplbot pricechanges`
=> Adds PriceChangedMonitoring

src/Directory.Build.targets, src/FplBot.Tests/TestBuilder.cs, src/FplBot.WebApi.Tests/RedisIntegrationTests.cs, src/FplBot.WebApi/Controllers/OAuthController.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/ISlackTeamRepository.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplBotJoinedChannelHandler.cs, src/Slackbot.Net.Extensions.FplBot/HelpEventHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/SlackWorkSpacePublisher.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
NB. Since this feature requires a re-install due to requesting 2 new scopes, it won't work for existing installs out of the box. 
Will post this message immediately when a user invites it into any channel:
=> Makes fplbot introduce itself when it's invited into a channel

src/FplBot.WebApi.Tests/RedisIntegrationTests.cs, src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs
=> Adds updateLeagueId method in RedisRepo

.github/workflows/CI.yml, .github/workflows/Release.yml, src/FplBot.sln
Halverer kjøretiden, ser det ut til
=> 🐧 Bytter CI til Linux builds

src/FplBot.WebApi/Pages/Admin/Broadcast.cshtml, src/FplBot.WebApi/Pages/Admin/Broadcast.cshtml.cs, src/FplBot.WebApi/Pages/Admin/Index.cshtml
=> Adds a admin/broadcast page

src/Directory.Build.targets, src/Slackbot.Net.Extensions.FplBot/HelpEventHandler.cs
Unknown in that Slackbot.NET does not have a model for it
=> Showcase hack for handling unknown events

src/Directory.Build.targets, src/FplBot.WebApi/appsettings.json, src/Slackbot.Net.Extensions.FplBot/Handlers/AppHomeOpenedEventHandler.cs, src/Slackbot.Net.Extensions.FplBot/HelpEventHandler.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Did a quick test. Just a spike for now, does not do anything useful with the view. Not sure how to receive data from the view yet (might be an interactive payload? 🤷‍♂️).
=> Adds `app_home_opened` event handler sample

src/Slackbot.Net.Extensions.FplBot/Extensions/ClassicLeagueEntryExtensions.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/CaptainsByGameWeek.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs
=> Use `new_entries`when no `standings` are available

src/Slackbot.Net.Extensions.FplBot/RecurringActions/GameweekLifecycleRecurringAction.cs
=> Bugfix:  emit gameweek just began for gw1

src/Directory.Build.targets, src/FplBot.WebApi/Startup.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplBotJoinedChannelHandler.cs
=> Only show intro notification when fplbot itself joins a channel

src/Directory.Build.targets, src/Slackbot.Net.Extensions.FplBot/Handlers/AppHomeOpenedEventHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/SlackWorkSpacePublisher.cs
Debugging which workspaces having fplbot subscriptions on non-existant slack channels
=> Adds more details to logs on slack api failures

src/Directory.Build.targets, src/FplBot.WebApi/Pages/Admin/Broadcast.cshtml, src/FplBot.WebApi/Pages/Admin/Index.cshtml, src/FplBot.WebApi/Pages/Admin/Index.cshtml.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails.cshtml.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/GameweekLeagueContext.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs
To be able to debug state during ongoing gameweeks
=> Adds some more debugging info in a team details page

src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs, src/FplBot.WebApi/FplBot.WebApi.csproj, src/FplBot.WebApi/Pages/Admin/Index.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails/Edit.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails/Edit.cshtml.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IFetchFplbotSetup.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/ISlackTeamRepository.cs
For fixing some obvious misconfigs during our install process ...
=> Simple channel+league modify page

src/FplBot.Tests/Helpers/Factory.cs, src/FplBot.Tests/Helpers/InMemorySlackTeamRepository.cs, src/FplBot.WebApi/Controllers/OAuthController.cs, src/FplBot.WebApi/Data/RedisSlackTeamRepository.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/FplbotSetup.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/ISlackWorkSpacePublisher.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/GameweekEndedNotifier.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/GameweekStartedNotifier.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplStandingsCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/SlackWorkSpacePublisher.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Mostly a cleanup PR. We had two interfaces for basically the same concept.
=> Remove IFetchFplSetup interface

src/Slackbot.Net.Extensions.FplBot/Constants.cs
=> Fix spelling of “jeez”

src/FplBot.WebApi/Pages/Admin/TeamDetails/Edit.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails/Edit.cshtml.cs
=> Simple modify subs page in edit team ui

src/FplBot.Tests/StateTests.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/GameweekLeagueContext.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsHandler.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/GameweekEventsFormatter.cs
Gjør eventhandler litt dummere, og flytter state-logikk til state.
=> Simplify OnFixtureEventHandler

src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/FixtureEventsHandlerV2.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/PriceChangeHandler.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/PriceChangeHandlerV2.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StateEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Forsøk på å flytte ting store dictionaries ut av minnet, og heller utføre lookups når eventer oppstår
=> Adds beta handlers with less state in-mem

src/Fpl.Client/Models/Player.cs, src/FplBot.Tests/PriceMonitorTests.cs, src/FplBot.Tests/StateTests.cs, src/FplBot.Tests/TestBuilder.cs, src/FplBot.WebApi/Controllers/TestController.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/PlayerPriceComparer.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StateEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StatusUpdateHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/PlayerChangesEventsExtractor.cs, src/Slackbot.Net.Extensions.FplBot/Models/PlayerStatusUpdate.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs
Beta-tester litt, og filtrerer derfor på Blank workspace på events. Har heller ikke lagt til ny event type i subs.
=> Status updates

src/FplBot.Tests/PlayerStatusUpdateTests.cs, src/FplBot.WebApi/Controllers/TestController.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StatusUpdateHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/PlayerChangesEventsExtractor.cs, src/Slackbot.Net.Extensions.FplBot/Models/PlayerStatusUpdate.cs
Mer beta-mas: si ifra hvis endring i "sjanse-for-å-spille" (eks. økt sannsynlighet 50% -> 75%).
=> +/- chance of playing changes

src/FplBot.Tests/PlayerStatusUpdateTests.cs, src/FplBot.Tests/StateTests.cs, src/FplBot.WebApi/Controllers/TestController.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StatusUpdateHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/PlayerChangesEventsExtractor.cs, src/Slackbot.Net.Extensions.FplBot/Models/PlayerStatusUpdate.cs
Tester filteret: ownership > 1 % evt pris over £5.0m
=> Filter important status updates only

src/Fpl.Client/Models/Fixture.cs, src/FplBot.Tests/GameweekMonitorOrchestratorTests.cs, src/FplBot.Tests/MatchStatusTests.cs, src/FplBot.Tests/PremierLeagueScraperApiTests.cs, src/FplBot.Tests/TestBuilder.cs, src/FplBot.WebApi/Controllers/TestController.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IGetMatchDetails.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IMatchStateMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/GameweekMonitorOrchestrator.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/LineupReadyHandler.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/MatchDetailsMapper.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/MatchState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/MatchStateMonitor.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/Models/Lineups.cs, src/Slackbot.Net.Extensions.FplBot/PremierLeagueScraperApi.cs, src/Slackbot.Net.Extensions.FplBot/SlackBotBuilderExtensions.cs, src/Slackbot.Net.Extensions.FplBot/Slackbot.Net.Extensions.FplBot.csproj
Meget hacky forsøk på å få til lagoppstillinger-notification
=> Adds lineup notifications

src/FplBot.Tests/StateTests.cs, src/FplBot.Tests/TestBuilder.cs, src/FplBot.WebApi/Controllers/TestController.cs, src/Slackbot.Net.Extensions.FplBot/Abstractions/IState.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/State.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StateEventsMonitor.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/StatusUpdateHandler.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/LiveEventsExtractor.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/PlayerChangesEventsExtractor.cs, src/Slackbot.Net.Extensions.FplBot/Models/FinishedFixture.cs
=> Match fulltime notification

src/FplBot.Tests/FplHandlersTests.cs, src/FplBot.Tests/Helpers/Factory.cs, src/Slackbot.Net.Extensions.FplBot/Extensions/StringExtensions.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplCaptainCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplChangeLeagueIdHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplInjuryCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplNextGameweekCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplPlayerCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplPricesHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplStandingsCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplSubscribeCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplSubscriptionsCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplTransfersCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/HandleAppMentionBase.cs
=> Make sure that handlers only respond to their own command

.gitignore, src/FplBot.WebApi/FplBot.WebApi.csproj, src/FplBot.WebApi/Program.cs, src/FplBot.WebApi/Properties/launchSettings.json, src/FplBot.WebApi/Startup.cs, src/FplBot.WebApi/appsettings.Development.json, src/Slackbot.Net.Extensions.FplBot/ILoggerExtensions.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/GameweekLifecycleRecurringAction.cs, src/Slackbot.Net.Extensions.FplBot/RecurringActions/NearDeadlineRecurringAction.cs
- Legger til litt metadata/korrelasjon på logs
- Går over til json logs i Heroku, mens lokalt logges det som før
=> Changes logging in Heroku to JSON lines

src/Slackbot.Net.Extensions.FplBot/RecurringActions/NearDeadlineRecurringAction.cs
Solves https://github.com/fplbot/fplbot/issues/119
=> Notify 24h before deadline, w/o @channel

src/FplBot.Tests/Formatting/FormatGameweekFinishedTests.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/GameweekEndedNotifier.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/Formatter.cs
=> Enable @skjelbek pallen gw end msg for all teamz

src/Slackbot.Net.Extensions.FplBot/Abstractions/ISlackTeamRepository.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/LineupReadyHandler.cs, src/Slackbot.Net.Extensions.FplBot/GameweekLifecycle/Handlers/NearDeadlineHandler.cs
=> Feature: move deadline/lineup events to subscriptions

src/FplBot.Tests/FplHandlersTests.cs, src/FplBot.Tests/MessageHelperTests.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplCaptainCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplChangeLeagueIdHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplInjuryCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplNextGameweekCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplPlayerCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplPricesHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplStandingsCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplSubscribeCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplSubscriptionsCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/FplTransfersCommandHandler.cs, src/Slackbot.Net.Extensions.FplBot/Handlers/HandleAppMentionBase.cs, src/Slackbot.Net.Extensions.FplBot/Helpers/MessageHelper.cs, test.http
Refactored HandleAppMentionBase for multiple commands support
=> Bugfix: Unsubscribing events

src/FplBot.Core/Handlers/FplEvents/GameweekEndedHandler.cs, src/FplBot.Core/Handlers/PublishStandingsCommandHandler.cs, src/FplBot.Core/Handlers/SlackEvents/FplStandingsCommandHandler.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/PublishEvent.cshtml, src/FplBot.WebApi/Pages/Admin/TeamDetails/PublishEvent.cshtml.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml
- Only supports Standings for now
=> Publishing of event from admin UI

src/FplBot.Core/Data/VerifiedEntriesRepository.cs, src/FplBot.Core/Handlers/InternalCommands/ConnectEntryToPLPlayerCommandHandler.cs, src/FplBot.Core/Handlers/InternalCommands/UpdateEntryStatsCommandHandler.cs, src/FplBot.Core/Handlers/InternalCommands/UpdateSelfishStatsCommandHandler.cs, src/FplBot.WebApi/Controllers/VirtualLeaguesController.cs, src/FplBot.WebApi/Pages/Admin/Verified.cshtml, src/FplBot.WebApi/Pages/Admin/Verified.cshtml.cs, src/FplBot.WebApi/wwwroot/css/site.css
=> Feature/improve verified admin UI

src/Fpl.Search/Searching/SearchService.cs, src/FplBot.WebApi/Controllers/SearchController.cs
=> Adds global search

src/Fpl.Search/Searching/SearchService.cs
Gives better matches imo. Supports searching with quotes.
=> Switch from multimatch to querystring search

src/FplBot.WebApi/Startup.cs
* Now requires access to the fplbot workspace && userids of @skjelbek , @johnkors , @kristianeaw
=> Change admin access policy

src/Fpl.Workers/Events/PublicEvents.cs, src/Fpl.Workers/RecurringActions/MatchDayStatusMonitor.cs, src/FplBot.Core/Handlers/FplEvents/MatchDayStatusHandler.cs
No handlers other than logging for now. Want to see how often this occur, and what the changes are
=> Adds emitting of League status changed events

src/FplBot.Core/Helpers/Formatting/Formatter.cs
=> Removes (joined this gw) from standings if 1st gw

src/Fpl.Search/Searching/SearchService.cs
=> Escape reserved elastic chars in query

src/FplBot.Core/Handlers/FplEvents/MatchDayStatusHandler.cs, src/FplBot.Core/Handlers/InternalCommands/UpdateSelfishStatsCommandHandler.cs, src/FplBot.Core/Handlers/InternalCommands/UpdateVerifiedEntriesCurrentGwPointsCommandHandler.cs
Changes when we do updates of verified entries points (currentgw + total) to a later point on each match day.
=> Update gw points for verified entries on leagues updated

src/FplBot.WebApi/Startup.cs, src/ext/Slackbot.Net.Endpoints/Authentication/AuthenticationBuilderExtensions.cs, src/ext/Slackbot.Net.Endpoints/Authentication/SlackbotEventsAuthenticationAuthenticationHandler.cs, src/ext/Slackbot.Net.Endpoints/Hosting/IAppBuilderExtensions.cs, src/ext/Slackbot.Net.Endpoints/Middlewares/SlackbotEventAuthMiddleware.cs, test.http
- Adds verification of slack callbacks actually coming from … Slack. And not anyone with cURL. 
- Source: https://api.slack.com/authentication/verifying-requests-from-slack
- 😳
- 🙈
- 😱
=> Adds signature verification

src/Fpl.Workers/Events/PublicEvents.cs, src/Fpl.Workers/RecurringActions/MatchDayStatusMonitor.cs, src/Fpl.Workers/States/State.cs, src/FplBot.Core/Handlers/FplEvents/MatchDayStatusHandler.cs, src/FplBot.Messaging.Contracts/Events/v1/MatchdayBonusPointsAdded.cs, src/FplBot.Messaging.Contracts/Events/v1/MatchdayLeaguesUpdated.cs, src/FplBot.Messaging.Contracts/Events/v1/MatchdayMatchPointsAdded.cs, src/FplBot.Messaging.Contracts/Events/v1/NewPlayersRegistered.cs, src/FplBot.Tests/MatchDayStatusMonitorTests.cs
- Bonus points added
- Match points added
- Leagues updated
=> Moves matchday status messaging to ASB

src/FplBot.Core/Handlers/SlackEvents/FplFollowLeagueHandler.cs, src/FplBot.Data/Abstractions/ISlackTeamRepository.cs, src/FplBot.Data/Repositories/Redis/SlackTeamRepository.cs, src/FplBot.Tests/Helpers/Factory.cs, src/FplBot.WebApi/Configurations/OAuthOptions.cs, src/FplBot.WebApi/Controllers/OAuthController.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml.cs, src/FplBot.WebApi/Startup.cs, src/ext/Slackbot.Net.Endpoints/Configurations/ITokenStore.cs, src/ext/Slackbot.Net.Endpoints/Hosting/IAppBuilderExtensions.cs, src/ext/Slackbot.Net.Endpoints/Hosting/ServiceCollectionExtensions.cs, src/ext/Slackbot.Net.Endpoints/Middlewares/SlackbotCodeTokenExchangeMiddleware.cs, src/ext/Slackbot.Net.Endpoints/OAuth/OAuthClient.cs, test.http
=> Move OAuth install flow to Slackbot.NET

src/Fpl.Workers/Models/Mappers/LiveEventsExtractor.cs, src/FplBot.Formatting/FixtureStats/GameweekEventsFormatter.cs, src/FplBot.Messaging.Contracts/Events/v1/FixtureEventsUpdated.cs, src/FplBot.Tests/Formatting/FixtureEventsFormattingTests.cs, src/FplBot.Tests/GetUpdatedFixtureEventsTests.cs, src/FplBot.Tests/Helpers/TestBuilder.cs, src/FplBot.WebApi/Controllers/DebugController.cs
=> Adds time to fixture events

src/Fpl.Client/Models/GameweekExtensions.cs, src/FplBot.Discord/Handlers/FplEvents/FixtureEventsHandler.cs, src/FplBot.Formatting/FixtureStats/TauntData.cs, src/FplBot.Slack/Handlers/FplEvents/FixtureEventsHandler.cs, src/FplBot.Slack/Handlers/SlackEvents/FplSearchHandler.cs, src/FplBot.Slack/Handlers/SlackEvents/FplStandingsCommandHandler.cs, src/FplBot.WebApi/Pages/Admin/TeamDetails/PublishEvent.cshtml.cs, src/FplBot.WebApi/Pages/Admin/Verified.cshtml.cs
No matching with Discord handles yet, just a simple entry name taunt
=> Discord: add fixture event taunts

src/FplBot.Formatting/FixtureStats/Formatters/RegularFormatter.cs, src/FplBot.Formatting/FixtureStats/Formatters/TauntyFormatter.cs, src/FplBot.Tests/Formatting/FixtureEventsFormattingTests.cs, src/FplBot.Tests/Helpers/TestBuilder.cs
=> Fixture events: fullname -> webname

src/FplBot.WebApi/Pages/Admin/Discord/Subscriptions.cshtml, src/FplBot.WebApi/Pages/Admin/Discord/Subscriptions.cshtml.cs
UI tweak. Groups subs in servers. Shows stats.
=> Admin UI: Update Discord page

src/Fpl.Search.Indexer.Console/Program.cs, src/FplBot.WebApi/Infrastructure/WebApplicationBuilderExtensions.cs
Moves indexing job to a separate, dedicated console app & container in Heroku
=> Moves indexing to sep worker

src/FplBot.Messaging.Contracts/Events/v1/Deadline.cs, src/FplBot.Messaging.Contracts/Events/v1/FixtureEventsUpdated.cs, src/FplBot.Messaging.Contracts/Events/v1/FixtureFinished.cs, src/FplBot.Messaging.Contracts/Events/v1/GameweekJustBegan.cs, src/FplBot.Messaging.Contracts/Events/v1/LineupReady.cs
Some handling does not make sense if handling is very late
=> NSB: Adds TimeToBeReceived for live events

src/FplBot.EventHandlers.Console/FplBot.EventHandlers.Console.csproj, src/FplBot.EventHandlers.Console/HostBuilderExtensions.cs
[Docs](https://docs.particular.net/tutorials/monitoring-setup/#smoke-test)
Enables monitoring in _ServicePulse_:
=> NSB: Adds metrics

src/Fpl.Client/Clients/FplClientOptionsConfigurator.cs, src/Fpl.Client/Clients/FplHttpHandler.cs, src/Fpl.Client/Infra/IFplApiClientServiceCollectionExtensions.cs
Hva skjer hvis vi bare fjerner auth?
=> Remove FPL auth

src/Fpl.Client/Abstractions/IEntryHistoryClient.cs, src/Fpl.Client/EntryHistoryClient.cs, src/Fpl.Search/Indexing/SlowEntryIndexProvider.cs, src/Fpl.Search/Models/EntryItem.cs, src/FplBot.VerifiedEntries/InternalCommands/UpdateEntryStatsCommandHandler.cs
Add Country, NumberOfPastSeasons and Thumbprint
=> Extend what to index on an entry

src/Fpl.EventPublishers/Models/Comparers/PlayersTeamChangeComparer.cs, src/Fpl.EventPublishers/Models/Mappers/PlayerChangesEventsExtractor.cs, src/Fpl.EventPublishers/RecurringActions/PlayerUpdatesRecurringAction.cs, src/FplBot.EventHandlers.Discord/NewPlayersHandler.cs, src/FplBot.EventHandlers.Slack/NewPlayerHandler.cs, src/FplBot.Formatting/Formatter.cs, src/FplBot.Messaging.Contracts/Events/v1/PremiershipPlayerTransferred.cs, src/FplBot.Tests/Helpers/TestBuilder.cs, src/FplBot.Tests/PlayerUpdatesRecurringActionTests.cs
Adds transfers from one PL team to another. Added as part of the "NewPlayers" notification.
=> Adds internal PL transfer notifications

src/Fpl.EventPublishers/Models/Mappers/PlayerChangesEventsExtractor.cs, src/FplBot.EventHandlers.Discord/NewPlayersHandler.cs, src/FplBot.Formatting/Formatter.cs
Small improvement on transfer messages.
=> Formatting: improves PL transfer message

src/FplBot.Infrastructure/Pulumi.Prod.yaml, src/FplBot.Infrastructure/Pulumi.Test.yaml
`fplbot-deployer` credentials were expired.
=> Updates Azure credentials in Pulumi

src/FplBot.EventHandlers.Discord/Helpers/PlayerExtensions.cs
Endrer threshold for å poste endringer til 0, så alle endringer kommer med
=> Change threshold

src/FplBot.EventHandlers.Slack/Helpers/PlayerExtensions.cs
Same as https://github.com/fplbot/fplbot/pull/331, but for Slack.
=> Remove threshold for posting changes to players to Slack

src/Fpl.EventPublishers/Models/Mappers/LiveEventsExtractor.cs, src/FplBot.Tests/GetUpdatedFixtureEventsTests.cs, src/FplBot.Tests/Helpers/TestBuilder.cs
Forgot about own goals being a separate stat.
Closes #336
=> Bugfix: Count own goals into score

src/FplBot.Formatting/FixtureStats/Describers/RedCardDescriber.cs, src/FplBot.Formatting/FixtureStats/TauntData.cs, src/FplBot.Tests/Formatting/FixtureEventsFormattingTests.cs
… instead of pr transfer.
Fixes #298.
=> Bugfix: multi taunts

src/FplBot.EventHandlers.Discord/Helpers/PlayerExtensions.cs, src/FplBot.EventHandlers.Slack/Helpers/PlayerExtensions.cs
=> Bugfix: Include zero percent ownership

src/FplBot.EventHandlers.Discord/GameweekFinishedHandler.cs, src/FplBot.EventHandlers.Discord/GameweekStartedHandler.cs, src/FplBot.EventHandlers.Slack/GameweekFinishedHandler.cs, src/FplBot.EventHandlers.Slack/GameweekStartedHandler.cs, src/FplBot.WebApi/Endpoints/Test/DebugRoute.cs, src/FplBot.WebApi/Endpoints/Test/Gameweekend/Get.cs
=> Don't notify if league has not started yet

src/FplBot.WebApi/Pages/Admin/TeamDetails/Show.cshtml.cs
For example missing a valid slack token to deliver notifications
=> admin: delete unauthed slack workspaces

src/FplBot.EventHandlers.Discord/NearDeadlineHandler.cs
They don't support @-mentions like @here
=> Discord: don't use embeds for deadline messages

src/FplBot.EventHandlers.Discord/BroadcastHandler.cs, src/FplBot.Messaging.Contracts/Commands/v1/BroadcastToDiscord.cs, src/FplBot.WebApi/Pages/Admin/Discord/Broadcast.cshtml, src/FplBot.WebApi/Pages/Admin/Discord/Broadcast.cshtml.cs
- Puts messages on a queue
- Filter: _all_ channels or channels subscribing to events requiring a league to follow
=> Adds broadcast to discord

src/FplBot.Tests/FplChangeLeagueIdHandlerTests.cs, src/FplBot.WebApi.Slack/Handlers/SlackEvents/FplFollowLeagueHandler.cs
=> Bugfix: handle tel:1234 in slack follow league cmd

deploytoprod.sh, deploytotest.sh, src/FplBot.Data/Discord/DiscordGuildStore.cs, src/FplBot.Data/Discord/IGuildRepository.cs, src/FplBot.WebApi.Slack/MetaService.cs, src/FplBot.WebApi/Endpoints/Test/DebugRoute.cs, src/FplBot.WebApi/Infrastructure/GuildStatusChecker.cs, src/FplBot.WebApi/Infrastructure/WebApplicationBuilderExtensions.cs, src/FplBot.WebApi/appsettings.json, src/ext/Discord.Net.HttpClients/DiscordClient.cs
Schedule task to remove any guilds & subs where fplbot is not a member.
=> Delete dead Discord installs
